server:
  port: 8088
spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 8
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          max-wait: -1
          min-idle: 0
          time-between-eviction-runs: -1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: false
  profiles:
    active: druid
  mvc:
    servlet:
      path: /
  application:
    name: exam
  main:
    allow-circular-references: true
jwt:
  exam:
    secret: cereshuzhitingnizhenbangcereshuzhitingnizhenbang
    expire: 8640000
  sys:
    secret: cereshuzhitingnizhenbangpoieshuzhitingnibangbang
    expire: 8640000
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
langchain4j:
  open-ai:
    chat-model:
      api-key: sk-979ebca6edb2485eab69f8f09feb42c3
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      base-url: https://api.deepseek.com